Hu c11 33/mvera
dlab-team/C11-Frontend pull request #10
Opened 2023-08-21 16:44 UTC by mauricioverar

se agrega constante social

2023-08-22 23:59 UTC, gonzafg2 requested changes

2023-08-22 23:59 UTC, gonzafg2 commented on src/components/Social_login.jsx
De los botones de social login no coinciden:
font-size, font-weight y line-height
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/95e41b62-07a4-4541-bed9-1be9b3cd1e61)
Por favor respetar el Figma

2023-08-23 01:38 UTC, mauricioverar commented on src/components/Social_login.jsx
se modifican estilos de fuentes en botones de Social_login
<img width="960" alt="05 fonts" src="https://github.com/dlab-team/C11-Frontend/assets/52289594/dd561a6d-43a8-485c-b4d9-a2ece505ba7b">

2023-08-23 19:51 UTC, mauricioverar commented on src/components/Social_login.jsx
fix: se modifican estilos de fuentes segun figma

2023-08-23 19:52 UTC, mauricioverar commented on src/components/Social_login.jsx
y agregan vinculos para vista Registro y 'Olvido de contraseña' RecoverPass

2023-08-30 02:18 UTC, gonzafg2 approved these changes

2023-08-30 02:19 UTC, merged