Hu c11 35/mvera
dlab-team/C11-Frontend pull request #11
Opened 2023-08-22 21:15 UTC by mauricioverar

se desarrolla vista para "olvido de contraseña"
<img width="960" alt="02" src="https://github.com/dlab-team/C11-Frontend/assets/52289594/a78efc0b-e6a8-4013-bd39-78d37f365c57">
<img width="299" alt="01" src="https://github.com/dlab-team/C11-Frontend/assets/52289594/5222e896-e0d1-4623-9281-30bc5c448bad">

2023-08-22 23:00 UTC, gonzafg2 requested changes
Qué gatilla mostrar el componente?

2023-08-22 23:03 UTC, mauricioverar commented
estaba esperando los pr anteriores para agregar el gatillo

El mar, 22 de ago. de 2023 7:00 p. m., Gonzalo Fleming <
***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> Qué gatilla mostrar el componente?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dlab-team/C11-Frontend/pull/11#pullrequestreview-1590451762>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMO6AOQI5C4QOJX6YPS2SOTXWU2YJANCNFSM6AAAAAA32QFPT4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-22 23:07 UTC, mauricioverar commented
<Link to="/recoverPass">
            <span className="px-4">¿Olvidaste tu contraseña?</span>
          </Link>

El mar, 22 ago 2023 a las 19:03, Mauricio Vera ***@***.***>)
escribió:

> estaba esperando los pr anteriores para agregar el gatillo
>
> El mar, 22 de ago. de 2023 7:00 p. m., Gonzalo Fleming <
> ***@***.***> escribió:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Qué gatilla mostrar el componente?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/dlab-team/C11-Frontend/pull/11#pullrequestreview-1590451762>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AMO6AOQI5C4QOJX6YPS2SOTXWU2YJANCNFSM6AAAAAA32QFPT4>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-08-22 23:09 UTC, mauricioverar commented
desde la vista login

El mar, 22 ago 2023 a las 19:07, Mauricio Vera ***@***.***>)
escribió:

> <Link to="/recoverPass">
>             <span className="px-4">¿Olvidaste tu contraseña?</span>
>           </Link>
>
> El mar, 22 ago 2023 a las 19:03, Mauricio Vera ***@***.***>)
> escribió:
>
>> estaba esperando los pr anteriores para agregar el gatillo
>>
>> El mar, 22 de ago. de 2023 7:00 p. m., Gonzalo Fleming <
>> ***@***.***> escribió:
>>
>>> ***@***.**** requested changes on this pull request.
>>>
>>> Qué gatilla mostrar el componente?
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/dlab-team/C11-Frontend/pull/11#pullrequestreview-1590451762>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AMO6AOQI5C4QOJX6YPS2SOTXWU2YJANCNFSM6AAAAAA32QFPT4>
>>> .
>>> You are receiving this because you authored the thread.Message ID:
>>> ***@***.***>
>>>
>>

2023-08-22 23:17 UTC, mauricioverar commented
se lo agregaré entonces y solicitaré el pr

El mar, 22 ago 2023 a las 19:09, Mauricio Vera ***@***.***>)
escribió:

> desde la vista login
>
> El mar, 22 ago 2023 a las 19:07, Mauricio Vera ***@***.***>)
> escribió:
>
>> <Link to="/recoverPass">
>>             <span className="px-4">¿Olvidaste tu contraseña?</span>
>>           </Link>
>>
>> El mar, 22 ago 2023 a las 19:03, Mauricio Vera ***@***.***>)
>> escribió:
>>
>>> estaba esperando los pr anteriores para agregar el gatillo
>>>
>>> El mar, 22 de ago. de 2023 7:00 p. m., Gonzalo Fleming <
>>> ***@***.***> escribió:
>>>
>>>> ***@***.**** requested changes on this pull request.
>>>>
>>>> Qué gatilla mostrar el componente?
>>>>
>>>> —
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/dlab-team/C11-Frontend/pull/11#pullrequestreview-1590451762>,
>>>> or unsubscribe
>>>> <https://github.com/notifications/unsubscribe-auth/AMO6AOQI5C4QOJX6YPS2SOTXWU2YJANCNFSM6AAAAAA32QFPT4>
>>>> .
>>>> You are receiving this because you authored the thread.Message ID:
>>>> ***@***.***>
>>>>
>>>

2023-08-25 01:34 UTC, gonzafg2 requested changes
Queda pendiente agregar la ruta según PR anterior, se espera

2023-08-30 15:04 UTC, gonzafg2 commented
PR de HU-34 aprobado, por favor incluir la ruta

2023-09-07 23:45 UTC, mauricioverar reviewed
ruta para recoverPass agregada

2023-09-07 23:55 UTC, mauricioverar reviewed
en Login.jsx se gatilla a recoverPass

2023-09-26 23:12 UTC, gonzafg2 approved these changes
ok

2023-09-26 23:12 UTC, merged