feat: pixels to rem
dlab-team/C11-Frontend pull request #12
Opened 2023-08-24 02:33 UTC by artem-liamichev

[FE] Cambiar pixels a rem en Formulario de Landing

enlace:
https://ddnadl.atlassian.net/browse/C11-51

2023-08-25 01:39 UTC, gonzafg2 requested changes
Sólo corregir el centrado del botón Enviar

2023-08-25 01:39 UTC, gonzafg2 commented on src/components/Landing/LandingForm.jsx
El botón enviar debe estar centrado según Figma
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/fdd3949f-b56d-4304-956a-f71895615418)
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/9c0f478f-46a7-4f93-9929-e6c7f0bb4acd)

2023-08-25 17:09 UTC, artem-liamichev commented on src/components/Landing/LandingForm.jsx
Corregido, 
iba un cambio en Figma, que paso después de commit

2023-08-30 02:27 UTC, gonzafg2 commented on src/components/Landing/LandingForm.jsx
Ok

2023-08-30 02:27 UTC, gonzafg2 approved these changes

2023-08-30 02:27 UTC, merged