Hu c11 45/mvera
dlab-team/C11-Frontend pull request #15
Opened 2023-08-25 19:20 UTC by mauricioverar

feat: se desarrolla vista celular y pc, para restablecer contraseña
<img width="308" alt="01" src="https://github.com/dlab-team/C11-Frontend/assets/52289594/f9bb8a70-1de9-48f0-8ba3-679de37419d0">
<img width="960" alt="02" src="https://github.com/dlab-team/C11-Frontend/assets/52289594/287b7868-22b3-4da0-b3be-b37682f75096">

2023-08-30 02:30 UTC, gonzafg2 requested changes
Por favor resolver los confictos

2023-09-07 23:57 UTC, mauricioverar reviewed
conflictos arreglados

2023-09-26 23:13 UTC, gonzafg2 approved these changes, later dismissed
ok

2023-09-26 23:55 UTC, mauricioverar reviewed
ok

2023-09-27 00:10 UTC, merged