Hu01 c11 22/liamichev
dlab-team/C11-Frontend pull request #6
Opened 2023-08-18 17:34 UTC by artem-liamichev

[https://ddnadl.atlassian.net/browse/C11-22?atlOrigin=eyJpIjoiYTdmZjk3Mzc3ODYzNDI0NmEwZDBhOTNmMjYxOWFmNDMiLCJwIjoiaiJ9](url)

https://ddnadl.atlassian.net/jira/software/projects/C11/boards/19?selectedIssue=C11-22

2023-08-22 23:58 UTC, gonzafg2 requested changes

2023-08-22 23:58 UTC, gonzafg2 commented on src/pages/landing/Home.jsx
El formulario se llama antes que el footer:
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/137b9350-7476-4b17-99e4-87e851ed9bac)
Corregir por favor

2023-08-23 00:37 UTC, artem-liamichev commented on src/pages/landing/Home.jsx
corregido

2023-08-23 01:50 UTC, mauricioverar approved these changes
todo ok, muy bien

2023-08-24 00:11 UTC, gonzafg2 approved these changes
Muy bien!

2023-08-24 00:11 UTC, gonzafg2 approved these changes

2023-08-24 00:12 UTC, gonzafg2 approved these changes

2023-08-24 00:12 UTC, merged