se desarrolla vista de formulario de registro
dlab-team/C11-Frontend pull request #7
Opened 2023-08-18 18:15 UTC by mauricioverar

<img width="960" alt="01" src="https://github.com/dlab-team/C11-Frontend/assets/52289594/551d0200-1a4c-437c-a9b8-e6e7ff0025ec">

2023-08-18 22:09 UTC, mauricioverar reviewed
todo ok

2023-08-21 15:10 UTC, mauricioverar commented
se agregan constantes

2023-08-22 23:59 UTC, gonzafg2 requested changes

2023-08-22 23:59 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
font-size, line-height no coinciden según Figma:
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/d9a1082a-69e0-421a-9b9f-b4b369c307a1)
Por favor revisar

2023-08-22 23:59 UTC, gonzafg2 commented on src/pages/access/Index.jsx
¿Cuál es la utilidad de este archivo? Si no tiene, eliminar.

2023-08-23 14:20 UTC, mauricioverar commented on src/components/forms/RegisterForm.jsx
fix: se modificaron fuentes según figma

2023-08-23 14:20 UTC, mauricioverar commented on src/pages/access/Index.jsx
fix: archivo Index.jsx eliminado

2023-08-25 01:13 UTC, gonzafg2 commented on src/pages/access/Index.jsx
Gracias Mauricio

2023-08-25 01:31 UTC, gonzafg2 requested changes
@mauricioverar por favor resolver lo indicado

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
El margen entre el nav y el título no corresponde 
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/853c96b3-5900-48ba-b334-34c1eaa01318)

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/82ccbebb-2c6d-428b-b742-91539c3a31d9)

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
La altura del input no se ajusta al Figma
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/4ae99667-16b7-4e4e-913e-6e0f38a976bd)
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/6a22e318-6715-4836-92cc-e0d8632eea44)

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
Muy bien Mauricio, corregido

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
El margen entre input y label no se ajusta al Figma
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/802eb74e-88e7-4d42-b0ef-0e30723f5084)
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/75c13d00-e0c8-495c-b0f0-d44ee612ff04)

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
La altura del botón de registrar no se ajusta al Figma
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/a3f4bfbf-805c-4516-921c-76ebddcb8699)
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/93d8ba12-5601-4033-92fd-701ff0a5b353)

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
El margen entre el último input y el botón no corresponde al Figma
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/01d90f9a-cacf-4f09-8398-8614223140af)
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/3947fec0-076d-43b1-8f34-36bb8c0e3bdd)

2023-08-25 01:31 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
El margen entre el botón y el footer no corresponde según el Figma
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/b388f035-36b1-4d81-9ec7-a1225ce17661)
![image](https://github.com/dlab-team/C11-Frontend/assets/5702027/0bc9199b-177a-4b6a-bf00-565e7af422b8)

2023-08-25 01:31 UTC, gonzafg2 commented
@mauricioverar tienes conflictos en el PR, por favor homologa esta rama con dev para resolverlos

2023-08-30 02:21 UTC, gonzafg2 requested changes
Hay conflictos pendientes de resolver. Por favor homologar con dev

2023-08-30 02:23 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
Ok

2023-08-30 02:23 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
Ok

2023-08-30 02:24 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
Ok

2023-08-30 02:25 UTC, gonzafg2 commented on src/components/forms/RegisterForm.jsx
Aun hay diferencias @mauricioverar por favor resolver

2023-08-30 15:02 UTC, merged

2023-08-30 15:05 UTC, mauricioverar reviewed
se modifica margen entre botón y footer

2023-08-30 15:05 UTC, mauricioverar commented on src/components/forms/RegisterForm.jsx
se modifica margen